# fly.toml app configuration file generated for physio-ai on 2025-07-05T21:54:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'physio-ai'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

# [deploy]
#   release_command = 'python scripts/setup_embeddings.py'

[env]
  LOCAL_MODE = '0'

[[mounts]]
  source = 'chroma_data'
  destination = '/app/chroma_db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
