app = "tu-nombre-de-app-aqui"  # lo define fly launch

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  LOCAL_MODE = "0"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "chroma_data"
  destination = "/app/chroma_db"

[deploy]
  release_command = "python scripts/setup_embeddings.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
